name: Run Gulp bundle

# Controls when the action will run.
on:
  push:
    # On which branch
    branches: ["master"]
    # On which files
    # paths: ["scripts/scripts.js", "styles/styles.scss"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'ui-bundle.zip'
          path: build/ui-bundle.zip
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}