name: Run Gulp bundle

# Controls when the action will run.
on:
  push:
    # On which branch
    branches: ["master"]
    # On which files
    # paths: ["scripts/scripts.js", "styles/styles.scss"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: gulp


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: LATEST
          release_name: Release LATEST
          body: |
            Release of the bundle-ui
          draft: true
          prerelease: true
  #     - name: Save ui-bundle
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ui-bundle
  #         path: build/ui-bundle.zip

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/download-artifact@v2
  #       id: download
  #       with:
  #         name: ui-bundle
  #     - name: 'Echo download path'